### ISSUE TITLE
KeyError: 'data' As of 2021-05-26

### ISSUE THREAD

**Issue by jeffc** [uvjustin/pyalarmdotcomajax#11]
As of this morning, it looks like something may have changed on the alarm.com end that's causing the json parsing to fail. Thanks for maintaining this package!

```
2021-05-26 13:11:56 ERROR (MainThread) [homeassistant.components.alarm_control_panel] Error while setting up alarmdotcom platform for alarm_control_panel
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 231, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/alarmdotcom/alarm_control_panel.py", line 96, in async_setup_platform
    await alarmdotcom.async_login()
  File "/config/custom_components/alarmdotcom/alarm_control_panel.py", line 156, in async_login
    await self._alarm.async_login()
  File "/var/tmp/venv/lib/python3.8/site-packages/pyalarmdotcomajax/pyalarmdotcomajax.py", line 206, in async_login
    return await self._async_get_system_info()
  File "/var/tmp/venv/lib/python3.8/site-packages/pyalarmdotcomajax/pyalarmdotcomajax.py", line 166, in _async_get_system_info
    self._systemid = json["data"][0]["id"]
KeyError: 'data'
```

**Comment by uvjustin** [comment]
https://github.com/uvjustin/alarmdotcom#two-factor-authentication
