### ISSUE TITLE
Alarm.com failures after 2021.12.1 update

### ISSUE THREAD

**Issue by pdobrien3** [uvjustin/pyalarmdotcomajax#13]
Logger: homeassistant.helpers.entity
Source: custom_components/alarmdotcom/alarm_control_panel.py:159
Integration: alarmdotcom (documentation)
First occurred: 9:56:45 AM (24 occurrences)
Last logged: 10:02:30 AM

Update for alarm_control_panel.alarm_com fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 487, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 691, in async_device_update
    raise exc
  File "/config/custom_components/alarmdotcom/alarm_control_panel.py", line 159, in async_update
    await self._alarm.async_update()
  File "/usr/local/lib/python3.9/site-packages/pyalarmdotcomajax/pyalarmdotcomajax.py", line 253, in async_update
    + sensor["attributes"]["stateText"]
KeyError: 'stateText'

**Comment by uvjustin** [comment]
Fixed in v.0.1.12
